Repository ramp4-pcar4/ramp4-pcar4, pull requests merged in 2024-11, with the labels that each got.

#2466 Add GitHub Action YAML for PR Slackbot
  .github/requirements.txt
  .github/slack-bot.py
  .github/workflows/slack-bot.yml
Labels: PR: Active, PR: Build

#2472 Make language change dropdown visible
  src/components/map/map-caption.vue
Labels: PR: Frontend

#2469 Add tooltip to basemap selection
  src/fixtures/basemap/screen.vue
Labels: PR: Frontend

#2492 Fix slackbot issues with double quotes
  .github/slack-bot.py
Labels: PR: Build

#2481 Update multi-ramp for export, correct selector
  demos/starter-scripts/multi-ramp.js
  src/fixtures/export-northarrow/index.ts
Labels: PR: Frontend

#2483 Version treeselect repo
  package-lock.json
  package.json
Labels: PR: Build
