Repository ramp4-pcar4/ramp4-pcar4, pull requests merged in 2024-12, with the labels that each got.

#2487 Implement better notification handling on lang switch
  src/api/instance.ts
Labels: PR: Frontend

#2489 Reduce initial download size
  src/fixtures/basemap/index.ts
  src/fixtures/details/index.ts
  src/fixtures/geosearch/index.ts
  src/fixtures/help/index.ts
  src/fixtures/layer-reorder/index.ts
  src/fixtures/legend/index.ts
  src/fixtures/metadata/index.ts
  src/fixtures/settings/index.ts
  src/fixtures/wizard/index.ts
  src/geo/esri.ts
  src/geo/layer/support/file-utils.ts
  src/geo/layer/support/ogc-utils.ts
  vite.config.ts
Labels: PR: Build

#2470 Fix focus issues with wizard
  package-lock.json
  src/components/panel-stack/panel-screen.vue
  src/fixtures/wizard/form-input.vue
  src/fixtures/wizard/screen.vue
  src/fixtures/wizard/stepper-item.vue
Labels: PR: Frontend

#2490 Update Vite to v6, full minify esDynamic
  package-lock.json
  package.json
  scripts/vite-minify-es-plugin.ts
  src/fixtures/settings/templates/input-control.vue
  tsconfig.node.json
  vite.config.ts
Labels: PR: Build

#2498 Fix pull request demo links when head branch is on main repo
  .github/workflows/demo-pr-links.yml
Labels: PR: Build

#2504 Switch to default codeql, npm overrides, and node 23.3.0 testing
  .github/workflows/codeql-analysis.yml
  .github/workflows/demo-build.yml
  .github/workflows/pr-checks.yml
  README.md
  docs/introduction/setup.md
  package-lock.json
  package.json
Labels: PR: Build

#2488 Add tooltip to grid for keyboard users
  src/fixtures/grid/lang/lang.csv
  src/fixtures/grid/table-component.vue
Labels: PR: Frontend

#2508 Change some docsite urls to avoid unwanted string substitution
  README.md
  docs/introduction/setup.md
Labels: PR: Build

#2512 add aria-label to floating-button component
  src/components/notification-center/floating-button.vue
Labels: PR: Frontend

#2502 Esri API 4.31
  README.md
  package-lock.json
  package.json
Labels: PR: Geo

#2474 Remove outer div from export, Make scrollable content tabbable
  src/components/panel-stack/panel-screen.vue
  src/fixtures/export/screen.vue
Labels: PR: Frontend

#2527 Fix basemap info tooltip issues, Fix various other tooltip issues
  src/components/notification-center/notification-list.vue
  src/components/panel-stack/panel-screen.vue
  src/fixtures/appbar/appbar.vue
  src/fixtures/basemap/item.vue
  src/fixtures/basemap/screen.vue
  src/fixtures/details/components/result-list.vue
  src/fixtures/details/components/symbology-list.vue
  src/fixtures/legend/screen.vue
  src/fixtures/mapnav/mapnav.vue
Labels: PR: Frontend

#2515 Make horizontal scrollbar visible, Add root element accessor, Fix grid tooltip
  docs/api-guides/instance.md
  package-lock.json
  package.json
  src/api/instance.ts
  src/fixtures/export/screen.vue
  src/fixtures/grid/table-component.vue
Labels: PR: Frontend

#2517 Fix wizard ts errors and correct ts check command
  package.json
  src/fixtures/wizard/screen.vue
Labels: PR: Build

#2528 Update eslint to latest, minor setting ajustments
  .eslintignore
  .eslintrc.cjs
  .github/workflows/demo-build.yml
  .github/workflows/demo-pr-links.yml
  .github/workflows/pr-checks.yml
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  docs/typedoc-README.md
  eslint.config.js
  package-lock.json
  package.json
  public/assets/logo.svg
  tailwind.config.cjs
  vite.config.ts
Labels: PR: Build

#2529 ESRI Chunk Load
  docs/using-ramp4/layers/fancy-properties.md
  src/api/instance.ts
  src/fixtures/overviewmap/overviewmap.vue
  src/geo/api/geo-defs.ts
  src/geo/esri.ts
  src/geo/layer/attrib-layer.ts
  src/geo/layer/feature-layer.ts
  src/geo/layer/file-layer.ts
  src/geo/layer/graphic-layer.ts
  src/geo/layer/imagery-layer.ts
  src/geo/layer/layer.ts
  src/geo/layer/map-image-layer.ts
  src/geo/layer/osm-tile-layer.ts
  src/geo/layer/support/file-utils.ts
  src/geo/layer/tile-layer.ts
  src/geo/layer/wms-layer.ts
  src/geo/map/basemap.ts
  src/geo/map/common-map.ts
  src/geo/map/overview-map.ts
  src/geo/map/ramp-map.ts
  src/geo/utils/query.ts
  src/geo/utils/symbology.ts
Labels: PR: Geo, PR: Build

#2536 Add back support for client side string template compilation
  vite.config.ts
Labels: PR: Build

#2537 Fix lint on column pin
  src/fixtures/grid/table-component.vue
Labels: PR: Build
