Repository ramp4-pcar4/ramp4-pcar4, pull requests merged in 2025-01, with the labels that each got.

#2542 Overview layer timeout race
  package-lock.json
  package.json
  src/geo/map/ramp-map.ts
Labels: PR: Geo

#2543 Generate d.ts typings for npm package
  package-lock.json
  package.json
  tsconfig.app.json
  vite.config.ts
Labels: PR: Build

#2560 Add new path input to fix main pr checks
  .github/workflows/demo-build.yml
Labels: PR: Build

#2555 Remove tooltip on select components for Firefox users
  src/fixtures/geosearch/top-filters.vue
  src/fixtures/wizard/form-input.vue
  src/lang/lang.csv
Labels: PR: Frontend

#2552 Fix empty button WAVE errors in grid
  src/components/panel-stack/controls/expand.vue
  src/fixtures/grid/lang/lang.csv
  src/fixtures/grid/table-component.vue
  src/fixtures/grid/templates/clear-filter.vue
  src/fixtures/grid/templates/details-button-renderer.vue
  src/fixtures/grid/templates/zoom-button-renderer.vue
Labels: PR: Frontend

#2548 Prevent image element from rendering when no logo in config
  src/components/map/map-caption.vue
Labels: PR: Frontend

#2547 Prevent direct modification of panelWidth within config object
  schema.json
  src/api/fixture.ts
Labels: PR: Active

#2551 Make Enter key work for first two data column headers
  src/fixtures/grid/accessibility.ts
Labels: PR: Frontend

#2561 Prevent tooltips on dropdown menus from being appended to parent
  src/components/controls/dropdown-menu.vue
Labels: PR: Frontend
